# Note: Common options can't be empty.

db.options.common:
  dbname: pengxwan_main_ndxz
  driver: pdo_mysql
  charset: utf8

db.info:
  table_prefix: ndxz_

monolog.options.common:
  monolog.name: 'silexhibit'

assetic.common:
  cache: true
  cache_bust: true

app.common:
  exhibit:
    max_image_sizes:
      - 200
      - 400
      - 600
      -
        name: full
        value: 9999
    thumbnail_sizes:
      - 100
      - 150
      - 200
    accepted_image_mimes:
      - image/jpeg
      - image/gif
      - image/png
      - image/webp
  content:
    application:
      name: Silexhibit
      url: 'http://hlfcoding.github.com/silexhibit'
      tip: >
        Silexhibit is a renovated Indexhibit using Silex and the best of open-source web libraries as a foundation.
    version: 0.0.1
