cms.common:

  helpers:
  view:
    coffee:
      - jquery.component
      - jquery.mixin
    js:
      - backbone
      - codemirror
      - codemirror-modes/*
      - foundation/foundation
      - foundation/foundation.*
      - jquery.fileupload/jquery.ui.widget
      - jquery.fileupload/canvas-to-blob
      - jquery.fileupload/jquery.iframe-transport
      - jquery.fileupload/load-image
      - jquery.fileupload/load-image-ios
      - jquery.fileupload/load-image-orientation
      - jquery.fileupload/load-image-meta
      - jquery.fileupload/load-image-exif
      - jquery.fileupload/load-image-exif-map
      - jquery.fileupload/jquery.fileupload
      - jquery.fileupload/jquery.fileupload-process
      - jquery.fileupload/jquery.fileupload-image
      - jquery.fileupload/jquery.fileupload-validate
      - moment
      - mustache
      - spectrum
      - underscore.inflection
      - underscore.string
    css:
      - codemirror
      - jquery.fileupload
      - spectrum
    js_templates:
      - exhibit-cell
      - exhibit-collection
      - exhibit-form
      - exhibit-form-section-main
      - exhibit-form-section-meta
      - exhibit-media-cell
      - exhibit-media-collection
      - exhibit-media-form
      - exhibit-section-form
      - form-text-editor
      - header
      - site-setting-form
      - user-setting-form
  content:
    copyright:
      start_year: 2012
      meta: >
        App is under an Attribution-Share Alike 3.0 Unported Creative Commons
        License.
      url: &copyright_source_url http://creativecommons.org/licenses/by-sa/3.0/
    sections:
      -
        name: exhibit
        title: Exhibits
    app_objects:
      -
        name: exhibit
        title: Exhibit

  head_links:
  metas:
  snippets:
